In [1]:
import pandas as pd
import numpy as np

In [2]:
crop = pd.read_csv("C:/Users/hp/Desktop/Sagar/Crop-Yeild-Prediction-gnanasagar/ml/data/raw/crop_yeild/crop_yield.csv")

weather = pd.read_csv(r"C:\Users\hp\Desktop\Sagar\Crop-Yeild-Prediction-gnanasagar\ml\data\raw\crop_yeild\state_weather_data_1997_2020.csv")

soil = pd.read_csv(r"C:\Users\hp\Desktop\Sagar\Crop-Yeild-Prediction-gnanasagar\ml\data\raw\crop_yeild\state_soil_data.csv")

faostat = pd.read_csv(r"C:\Users\hp\Desktop\Sagar\Crop-Yeild-Prediction-gnanasagar\ml\data\raw\FAOSTAT_data_en_7-26-2026.csv")

In [3]:
print("Hello SmartYield!")

Hello SmartYield!

In [4]:
print("Crop Dataset Shape:", crop.shape)
print("Weather Dataset Shape:", weather.shape)
print("Soil Dataset Shape:", soil.shape)
print("FAOSTAT Dataset Shape:", faostat.shape)

Crop Dataset Shape: (19689, 9)
Weather Dataset Shape: (720, 5)
Soil Dataset Shape: (30, 5)
FAOSTAT Dataset Shape: (15622, 15)

In [5]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   crop        19689 non-null  object
 1   year        19689 non-null  int64
 2   season      19689 non-null  object
 3   state       19689 non-null  object
 4   area        19689 non-null  float64
 5   production  19689 non-null  int64
 6   fertilizer  19689 non-null  float64
 7   pesticide   19689 non-null  float64
 8   yield       19689 non-null  float64
dtypes: float64(4), int64(2), object(3)
memory usage: 1.4+ MB

In [6]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 720 non-null    object
 1   year                  720 non-null    int64
 2   avg_temp_c            720 non-null    float64
 3   total_rainfall_mm     720 non-null    float64
 4   avg_humidity_percent  720 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 28.3+ KB

In [7]:
soil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   30 non-null     object
 1   N       30 non-null     int64
 2   P       30 non-null     int64
 3   K       30 non-null     int64
 4   pH      30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.3+ KB

In [8]:
faostat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15622 entries, 0 to 15621
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       15622 non-null  object
 1   Domain            15622 non-null  object
 2   Area Code (M49)   15622 non-null  int64
 3   Area              15622 non-null  object
 4   Element Code      15622 non-null  int64
 5   Element           15622 non-null  object
 6   Item Code (CPC)   15622 non-null  float64
 7   Item              15622 non-null  object
 8   Year Code         15622 non-null  int64
 9   Year              15622 non-null  int64
 10  Unit              15622 non-null  object
 11  Value             15490 non-null  float64
 12  Flag              15622 non-null  object
 13  Flag Description  15622 non-null  object
 14  Note              458 non-null    object
dtypes: float64(2), int64(4), object(9)
memory usage: 1.8+ MB

In [9]:
crop.isnull().sum()

crop          0
year          0
season        0
state         0
area          0
production    0
fertilizer    0
pesticide     0
yield         0
dtype: int64

In [10]:
weather.isnull().sum()

state                   0
year                    0
avg_temp_c              0
total_rainfall_mm       0
avg_humidity_percent    0
dtype: int64

In [11]:
soil.isnull().sum()

state    0
N        0
P        0
K        0
pH       0
dtype: int64

In [12]:
faostat.isnull().sum()

Domain Code             0
Domain                  0
Area Code (M49)         0
Area                    0
Element Code            0
Element                 0
Item Code (CPC)         0
Item                    0
Year Code               0
Year                    0
Unit                    0
Value                 132
Flag                    0
Flag Description        0
Note                15164
dtype: int64

In [13]:
print("Crop:", crop.duplicated().sum())

print("Weather:", weather.duplicated().sum())

print("Soil:", soil.duplicated().sum())

print("FAOSTAT:", faostat.duplicated().sum())

Crop: 0
Weather: 0
Soil: 0
FAOSTAT: 0

In [14]:
crop.describe()

,year,area,production,fertilizer,pesticide,yield
count,19689.000000,1.968900e+04,1.968900e+04,1.968900e+04,1.968900e+04,19689.000000
mean,2009.127584,1.799266e+05,1.643594e+07,2.410331e+07,4.884835e+04,79.954009
std,6.498099,7.328287e+05,2.630568e+08,9.494600e+07,2.132874e+05,878.306193
min,1997.000000,5.000000e-01,0.000000e+00,5.417000e+01,9.000000e-02,0.000000
25%,2004.000000,1.390000e+03,1.393000e+03,1.880146e+05,3.567000e+02,0.600000
50%,2010.000000,9.317000e+03,1.380400e+04,1.234957e+06,2.421900e+03,1.030000
75%,2015.000000,7.511200e+04,1.227180e+05,1.000385e+07,2.004170e+04,2.388889
max,2020.000000,5.080810e+07,6.326000e+09,4.835407e+09,1.575051e+07,21105.000000

In [15]:
weather.describe()

              year  avg_temp_c  total_rainfall_mm  avg_humidity_percent
count   720.000000  720.000000         720.000000            720.000000
mean   2008.500000   23.383389        1388.461083             64.825764
std       6.926999    4.968676         672.503842             12.148615
min    1997.000000    6.260000         249.240000             34.470000
25%    2002.750000   22.265000         914.985000             54.615000
50%    2008.500000   25.115000        1231.830000             68.710000
75%    2014.250000   26.580000        1702.595000             74.567500
max    2020.000000   28.630000        5363.280000             86.060000

In [16]:
soil.describe()

                N          P          K         pH
count   30.000000  30.000000  30.000000  30.000000
mean    75.566667  31.466667  33.333333   6.553333
std     22.730328  12.386682   7.594614   0.763717
min     50.000000  15.000000  20.000000   5.500000
25%     60.500000  20.000000  28.500000   5.900000
50%     70.000000  29.000000  34.500000   6.450000
75%     80.000000  41.500000  38.000000   7.075000
max    150.000000  55.000000  50.000000   8.000000

In [17]:
faostat.describe()

,Area Code (M49),Element Code,Item Code (CPC),Year Code,Year,Value
count,15622.0,15622.000000,15622.000000,15622.000000,15622.000000,1.549000e+04
mean,356.0,5412.542184,1318.768473,1992.841762,1992.841762,3.375330e+06
std,0.0,81.300354,442.745905,18.528100,18.528100,1.930403e+07
min,356.0,5312.000000,111.000000,1961.000000,1961.000000,0.000000e+00
25%,356.0,5312.000000,1242.000000,1977.000000,1977.000000,6.296625e+03
50%,356.0,5412.000000,1344.020000,1993.000000,1993.000000,1.000000e+05
75%,356.0,5510.000000,1610.000000,2009.000000,2009.000000,9.058375e+05
max,356.0,5510.000000,1970.000000,2024.000000,2024.000000,4.905334e+08

In [18]:
print("Crop duplicates:", crop.duplicated().sum())
print("Weather duplicates:", weather.duplicated().sum())
print("Soil duplicates:", soil.duplicated().sum())
print("FAOSTAT duplicates:", faostat.duplicated().sum())

Crop duplicates: 0
Weather duplicates: 0
Soil duplicates: 0
FAOSTAT duplicates: 0

In [19]:
crop_clean = crop.copy()
weather_clean = weather.copy()
soil_clean = soil.copy()
faostat_clean = faostat.copy()

In [20]:
print("Number of States:", crop_clean["state"].nunique())
print(crop_clean["state"].unique())

Number of States: 30
['Assam' 'Karnataka' 'Kerala' 'Meghalaya' 'West Bengal' 'Puducherry' 'Goa'
 'Andhra Pradesh' 'Tamil Nadu' 'Odisha' 'Bihar' 'Gujarat' 'Madhya Pradesh'
 'Maharashtra' 'Mizoram' 'Punjab' 'Uttar Pradesh' 'Haryana'
 'Himachal Pradesh' 'Tripura' 'Nagaland' 'Chhattisgarh' 'Uttarakhand'
 'Jharkhand' 'Delhi' 'Manipur' 'Jammu and Kashmir' 'Telangana'
 'Arunachal Pradesh' 'Sikkim']

In [21]:
print("Number of Crops:", crop_clean["crop"].nunique())
print(crop_clean["crop"].unique())

Number of Crops: 55
['Arecanut' 'Arhar/Tur' 'Castor seed' 'Coconut ' 'Cotton(lint)'
 'Dry chillies' 'Gram' 'Jute' 'Linseed' 'Maize' 'Mesta' 'Niger seed'
 'Onion' 'Other  Rabi pulses' 'Potato' 'Rapeseed &Mustard' 'Rice'
 'Sesamum' 'Small millets' 'Sugarcane' 'Sweet potato' 'Tapioca' 'Tobacco'
 'Turmeric' 'Wheat' 'Bajra' 'Black pepper' 'Cardamom' 'Coriander' 'Garlic'
 'Ginger' 'Groundnut' 'Horse-gram' 'Jowar' 'Ragi' 'Cashewnut' 'Banana'
 'Soyabean' 'Barley' 'Khesari' 'Masoor' 'Moong(Green Gram)'
 'Other Kharif pulses' 'Safflower' 'Sannhamp' 'Sunflower' 'Urad'
 'Peas & beans (Pulses)' 'other oilseeds' 'Other Cereals' 'Cowpea(Lobia)'
 'Oilseeds total' 'Guar seed' 'Other Summer Pulses' 'Moth']

In [22]:
crop_clean["state"] = crop_clean["state"].str.strip().str.title()

crop_clean["crop"] = crop_clean["crop"].str.strip().str.title()

crop_clean["season"] = crop_clean["season"].str.strip().str.title()

In [23]:
weather_clean["state"] = weather_clean["state"].str.strip().str.title()

soil_clean["state"] = soil_clean["state"].str.strip().str.title()

faostat_clean["Area"] = faostat_clean["Area"].str.strip().str.title()

faostat_clean["Item"] = faostat_clean["Item"].str.strip().str.title()

In [24]:
crop_clean["state"].unique()

array(['Assam', 'Karnataka', 'Kerala', 'Meghalaya', 'West Bengal',
       'Puducherry', 'Goa', 'Andhra Pradesh', 'Tamil Nadu', 'Odisha',
       'Bihar', 'Gujarat', 'Madhya Pradesh', 'Maharashtra', 'Mizoram',
       'Punjab', 'Uttar Pradesh', 'Haryana', 'Himachal Pradesh',
       'Tripura', 'Nagaland', 'Chhattisgarh', 'Uttarakhand', 'Jharkhand',
       'Delhi', 'Manipur', 'Jammu And Kashmir', 'Telangana',
       'Arunachal Pradesh', 'Sikkim'], dtype=object)

In [25]:
crop_clean["crop"].unique()

array(['Arecanut', 'Arhar/Tur', 'Castor Seed', 'Coconut', 'Cotton(Lint)',
       'Dry Chillies', 'Gram', 'Jute', 'Linseed', 'Maize', 'Mesta',
       'Niger Seed', 'Onion', 'Other  Rabi Pulses', 'Potato',
       'Rapeseed &Mustard', 'Rice', 'Sesamum', 'Small Millets',
       'Sugarcane', 'Sweet Potato', 'Tapioca', 'Tobacco', 'Turmeric',
       'Wheat', 'Bajra', 'Black Pepper', 'Cardamom', 'Coriander',
       'Garlic', 'Ginger', 'Groundnut', 'Horse-Gram', 'Jowar', 'Ragi',
       'Cashewnut', 'Banana', 'Soyabean', 'Barley', 'Khesari', 'Masoor',
       'Moong(Green Gram)', 'Other Kharif Pulses', 'Safflower',
       'Sannhamp', 'Sunflower', 'Urad', 'Peas & Beans (Pulses)',
       'Other Oilseeds', 'Other Cereals', 'Cowpea(Lobia)',
       'Oilseeds Total', 'Guar Seed', 'Other Summer Pulses', 'Moth'],
      dtype=object)

In [26]:
print(crop_clean["state"].unique())
print(crop_clean["crop"].unique())

['Assam' 'Karnataka' 'Kerala' 'Meghalaya' 'West Bengal' 'Puducherry' 'Goa'
 'Andhra Pradesh' 'Tamil Nadu' 'Odisha' 'Bihar' 'Gujarat' 'Madhya Pradesh'
 'Maharashtra' 'Mizoram' 'Punjab' 'Uttar Pradesh' 'Haryana'
 'Himachal Pradesh' 'Tripura' 'Nagaland' 'Chhattisgarh' 'Uttarakhand'
 'Jharkhand' 'Delhi' 'Manipur' 'Jammu And Kashmir' 'Telangana'
 'Arunachal Pradesh' 'Sikkim']
['Arecanut' 'Arhar/Tur' 'Castor Seed' 'Coconut' 'Cotton(Lint)'
 'Dry Chillies' 'Gram' 'Jute' 'Linseed' 'Maize' 'Mesta' 'Niger Seed'
 'Onion' 'Other  Rabi Pulses' 'Potato' 'Rapeseed &Mustard' 'Rice'
 'Sesamum' 'Small Millets' 'Sugarcane' 'Sweet Potato' 'Tapioca' 'Tobacco'
 'Turmeric' 'Wheat' 'Bajra' 'Black Pepper' 'Cardamom' 'Coriander' 'Garlic'
 'Ginger' 'Groundnut' 'Horse-Gram' 'Jowar' 'Ragi' 'Cashewnut' 'Banana'
 'Soyabean' 'Barley' 'Khesari' 'Masoor' 'Moong(Green Gram)'
 'Other Kharif Pulses' 'Safflower' 'Sannhamp' 'Sunflower' 'Urad'
 'Peas & Beans (Pulses)' 'Other Oilseeds' 'Other Cereals' 'Cowpea(Lobia)'
 'Oilseeds Total' 'Guar Seed' 'Other Summer Pulses' 'Moth']

In [27]:
weather_clean.columns

Index(['state', 'year', 'avg_temp_c', 'total_rainfall_mm',
       'avg_humidity_percent'],
      dtype='object')

In [28]:
soil_clean.columns

Index(['state', 'N', 'P', 'K', 'pH'], dtype='object')

In [29]:
crop_weather = pd.merge(
    crop_clean,
    weather_clean,
    on=["state", "year"],
    how="left"
)

In [30]:
print(crop_weather.shape)

(19689, 12)

In [31]:
crop_weather.head()

,crop,year,season,state,area,production,fertilizer,pesticide,yield,avg_temp_c,total_rainfall_mm,avg_humidity_percent
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,22.41,1468.92,70.71
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,631643.29,2057.47,0.710435,22.41,1468.92,70.71
2,Castor Seed,1997,Kharif,Assam,796.0,22,75755.32,246.76,0.238333,22.41,1468.92,70.71
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,1870661.52,6093.36,5238.051739,22.41,1468.92,70.71
4,Cotton(Lint),1997,Kharif,Assam,1739.0,794,165500.63,539.09,0.420909,22.41,1468.92,70.71

In [32]:
final_dataset = pd.merge(
    crop_weather,
    soil_clean,
    on="state",
    how="left"
)

In [33]:
print(final_dataset.shape)

(19689, 16)

In [34]:
final_dataset.head()

,crop,year,season,state,area,production,fertilizer,pesticide,yield,avg_temp_c,total_rainfall_mm,avg_humidity_percent,N,P,K,pH
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,22.41,1468.92,70.71,60,18,38,5.8
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,631643.29,2057.47,0.710435,22.41,1468.92,70.71,60,18,38,5.8
2,Castor Seed,1997,Kharif,Assam,796.0,22,75755.32,246.76,0.238333,22.41,1468.92,70.71,60,18,38,5.8
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,1870661.52,6093.36,5238.051739,22.41,1468.92,70.71,60,18,38,5.8
4,Cotton(Lint),1997,Kharif,Assam,1739.0,794,165500.63,539.09,0.420909,22.41,1468.92,70.71,60,18,38,5.8

In [35]:
final_dataset.isnull().sum()

crop                    0
year                    0
season                  0
state                   0
area                    0
production              0
fertilizer              0
pesticide               0
yield                   0
avg_temp_c              0
total_rainfall_mm       0
avg_humidity_percent    0
N                       0
P                       0
K                       0
pH                      0
dtype: int64

In [39]:
final_dataset.to_csv(
    "C:/Users/hp/Desktop/Sagar/Crop-Yeild-Prediction-gnanasagar/ml/data/processed/smartyield_dataset.csv",
    index=False
)

print("Dataset Saved Successfully!")

Dataset Saved Successfully!

In [40]:
import os

print(os.listdir("C:/Users/hp/Desktop/Sagar/Crop-Yeild-Prediction-gnanasagar/ml/data/processed"))

['smartyield_dataset.csv']